version: '3'

services:
  mosquitto:
    image: eclipse-mosquitto
    ports:
      - "1884:1883"
    volumes:
      - mosquitto-data:/mosquitto/data
      - mosquitto-log:/mosquitto/log

  backend:
    build: ./back
    depends_on:
      - mosquitto
    environment:
      - MQTT_BROKER=mosquitto

volumes:
  mosquitto-data:
  mosquitto-log:

